//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kraken.SharePoint.Caml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CamlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CamlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kraken.SharePoint.Caml.CamlResources", typeof(CamlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHyperLink.
        /// </summary>
        internal static string AutoHyperLink {
            get {
                return ResourceManager.GetString("AutoHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHyperLinkNoEncoding.
        /// </summary>
        internal static string AutoHyperLinkNoEncoding {
            get {
                return ResourceManager.GetString("AutoHyperLinkNoEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoNewLine.
        /// </summary>
        internal static string AutoNewLine {
            get {
                return ResourceManager.GetString("AutoNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginsWith.
        /// </summary>
        internal static string BeginsWith {
            get {
                return ResourceManager.GetString("BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentUserGroups.
        /// </summary>
        internal static string CurrentUserGroups {
            get {
                return ResourceManager.GetString("CurrentUserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateRangesOverlap.
        /// </summary>
        internal static string DateRangesOverlap {
            get {
                return ResourceManager.GetString("DateRangesOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eq.
        /// </summary>
        internal static string Eq {
            get {
                return ResourceManager.GetString("Eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldRef.
        /// </summary>
        internal static string FieldRef {
            get {
                return ResourceManager.GetString("FieldRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geq.
        /// </summary>
        internal static string Geq {
            get {
                return ResourceManager.GetString("Geq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBy.
        /// </summary>
        internal static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gt.
        /// </summary>
        internal static string Gt {
            get {
                return ResourceManager.GetString("Gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTMLEncode.
        /// </summary>
        internal static string HTMLEncode {
            get {
                return ResourceManager.GetString("HTMLEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNotNull.
        /// </summary>
        internal static string IsNotNull {
            get {
                return ResourceManager.GetString("IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNull.
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leq.
        /// </summary>
        internal static string Leq {
            get {
                return ResourceManager.GetString("Leq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        internal static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt.
        /// </summary>
        internal static string Lt {
            get {
                return ResourceManager.GetString("Lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        internal static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neq.
        /// </summary>
        internal static string Neq {
            get {
                return ResourceManager.GetString("Neq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderBy.
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectProperty.
        /// </summary>
        internal static string ProjectProperty {
            get {
                return ResourceManager.GetString("ProjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPGroup.
        /// </summary>
        internal static string SPGroup {
            get {
                return ResourceManager.GetString("SPGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPWeb.AllUsers.
        /// </summary>
        internal static string SPWebAllUsers {
            get {
                return ResourceManager.GetString("SPWebAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPWeb.Groups.
        /// </summary>
        internal static string SPWebGroups {
            get {
                return ResourceManager.GetString("SPWebGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPWeb.Users.
        /// </summary>
        internal static string SPWebUsers {
            get {
                return ResourceManager.GetString("SPWebUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StripWS.
        /// </summary>
        internal static string StripWS {
            get {
                return ResourceManager.GetString("StripWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuff.
        /// </summary>
        internal static string Stuff {
            get {
                return ResourceManager.GetString("Stuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLEncode.
        /// </summary>
        internal static string URLEncode {
            get {
                return ResourceManager.GetString("URLEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLEncodeAsURL.
        /// </summary>
        internal static string URLEncodeAsURL {
            get {
                return ResourceManager.GetString("URLEncodeAsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewFields.
        /// </summary>
        internal static string ViewFields {
            get {
                return ResourceManager.GetString("ViewFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webs.
        /// </summary>
        internal static string Webs {
            get {
                return ResourceManager.GetString("Webs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        internal static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithIndex.
        /// </summary>
        internal static string WithIndex {
            get {
                return ResourceManager.GetString("WithIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
