//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kraken.SharePoint.Cloud.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/Lists.asmx")]
        public string Kraken_SharePoint_Cloud_ListsWS_Lists {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_ListsWS_Lists"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/Webs.asmx")]
        public string Kraken_SharePoint_Cloud_WebsWS_Webs {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_WebsWS_Webs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/Sites.asmx")]
        public string Kraken_SharePoint_Cloud_SitesWS_Sites {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_SitesWS_Sites"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/SiteData.asmx")]
        public string Kraken_SharePoint_Cloud_SiteDataWS_SiteData {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_SiteDataWS_SiteData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/Search.asmx")]
        public string Kraken_SharePoint_Cloud_SearchWS_QueryService {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_SearchWS_QueryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/SPSearch.asmx")]
        public string Kraken_SharePoint_Cloud_SPSearchWS_QueryService {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_SPSearchWS_QueryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/ExcelService.asmx")]
        public string Kraken_SharePoint_Cloud_ExcelServiceWS_ExcelService {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_ExcelServiceWS_ExcelService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/WebPartPages.asmx")]
        public string Kraken_SharePoint_Cloud_WebPartPagesWS_WebPartPagesWebService {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_WebPartPagesWS_WebPartPagesWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/UserProfileService.asmx")]
        public string Kraken_SharePoint_Cloud_UserProfileServiceWS_UserProfileService {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_UserProfileServiceWS_UserProfileService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/Views.asmx")]
        public string Kraken_SharePoint_Cloud_ViewsWS_Views {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_ViewsWS_Views"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://portal.red.lab.colossusconsulting.com/_vti_bin/Authentication.asmx")]
        public string Kraken_SharePoint_Cloud_AuthenticationWS_Authentication {
            get {
                return ((string)(this["Kraken_SharePoint_Cloud_AuthenticationWS_Authentication"]));
            }
        }
    }
}
